### ISSUE TITLE
Dark theme to dark on v0.4.0

### ISSUE THREAD

**Issue by M00NJ** [itsmartashub/floristyle#7] opened 2024-03-11 11:02 UTC
Florisboard got an update yesterday and the dark theme looks much darker now. It's very close to the oled theme. I tried reimporting but it stayed like this. I don't know if the other themes changed as well since I only used this one.

**Comment by itsmartashub** [comment] 2024-03-11 13:07
Yes, it's quite an unpleasant experience for the eyes.

I'm not sure if any Material You-related dependency was updated with the latest Florisboard update because I noticed that in other Material You Android applications as well, the palette of dynamically available colors has changed with the recent updates.

I hope the [latest floristyle update](https://github.com/itsmartashub/floristyle/releases/tag/v.2.1.1) has at least resolved some issues with colors in dark themes.

**Comment by M00NJ** [comment] 2024-03-11 13:58
Thanks for the quick response :) I installed the new version of your theme. Unfortunatwly the dark and darker variants are all borderless now.

![Screenshot_20240311-145445.png](https://github.com/itsmartashub/floristyle/assets/82398591/0a6e04b3-02fa-4fdb-819a-e0f720fb68f0)

![Screenshot_20240311-145453.png](https://github.com/itsmartashub/floristyle/assets/82398591/533a06d6-fb4a-402c-bd25-869ebf4ebae3)

![Screenshot_20240311-145502.png](https://github.com/itsmartashub/floristyle/assets/82398591/cce1fde7-9483-4aeb-a41c-5e20e014a9cc)

![Screenshot_20240311-145511.png](https://github.com/itsmartashub/floristyle/assets/82398591/64367b37-fc61-426f-8540-5c4a2fccc452)

**Comment by itsmartashub** [comment] 2024-03-11 16:04
What is your Android version?

I've checked with a few different devices (all **Android 13** tho, so **not tested** on **A14**), and I couldn't reproduce the issue you're having.
Everything seems fine, except that some color shades for certain elements are still more aggressive then in previous [`v0.4.0-alpha06`](https://github.com/florisboard/florisboard/releases/tag/v0.4.0-alpha06) version, but I can't do anything about that at the moment, as it's the color palette that the Material You version used in Florisboard offers.

**Comment by M00NJ** [comment] 2024-03-11 21:05
Yeah, I'm on Android 14 (GrapheneOS). Since MD3 is pretty new they are might still do small changes to the color roles in between Android updates. But then I wonder why this wasn't happening before the update. Seems more likely that there were changes made to how Florisboard handles the colors. I played around with the system color because I got curios and if you select one of the two-toned color options you can see a very small difference between the buttons and background. But all single color options have this issue, so you're right. It's two color with the same value. This might have to be addressed over at Florisboard.

**Comment by itsmartashub** [comment] 2024-04-23 17:28
Hey @M00NJ, it would be great if you could confirm if this issue has been fixed with the latest versions of [Florisboard `v0.4.0-beta02`](https://github.com/florisboard/florisboard/releases/tag/v0.4.0-beta02) and [Floristyle `v3.0.0`](https://github.com/itsmartashub/floristyle/releases/tag/v3.0.0) so that this issue can be closed peacefully

**Comment by M00NJ** [comment] 2024-04-23 17:53
I can confirm the issue is fixed :)

**Closed** 2024-04-23 19:17 UTC
